# Generated by Django 3.1 on 2020-09-12 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0006_auto_20200912_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TimeSlots',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=150, null=True)),
                ('meeting_status', models.CharField(max_length=150, null=True)),
                ('meeting_description', models.TextField(null=True)),
                ('meeting_date', models.DateTimeField()),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.learner')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion_app.timeslot')),
            ],
            options={
                'verbose_name_plural': 'Meetings',
            },
        ),
    ]
