# Generated by Django 3.1 on 2020-09-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_app', '0002_auto_20200913_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_date',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
