# Generated by Django 3.1 on 2020-09-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_app', '0003_auto_20200919_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
