# Generated by Django 3.1 on 2020-09-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20200911_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name_plural': 'Lectures'},
        ),
    ]
