# Generated by Django 3.1 on 2020-09-12 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_auto_20200912_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='chapter',
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.course'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_subject',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
