# Generated by Django 3.1 on 2020-09-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_auto_20200912_0500'),
        ('course_app', '0007_auto_20200912_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.learner'),
        ),
    ]
