# Generated by Django 3.1 on 2020-09-12 14:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0008_auto_20200912_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name_plural': 'Enrollments'},
        ),
        migrations.CreateModel(
            name='EnrollmentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 12, 14, 2, 37, 52389, tzinfo=utc))),
                ('recipient', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'EnrollmentNotifications',
            },
        ),
    ]
