# Generated by Django 3.1 on 2020-09-12 21:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0009_auto_20200912_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentnotification',
            name='read',
        ),
        migrations.RemoveField(
            model_name='enrollmentnotification',
            name='sender',
        ),
        migrations.AddField(
            model_name='enrollmentnotification',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.enrollment'),
        ),
        migrations.AlterField(
            model_name='enrollmentnotification',
            name='message',
            field=models.TextField(default='Your enrolment is complete'),
        ),
        migrations.AlterField(
            model_name='enrollmentnotification',
            name='notification_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 12, 21, 6, 49, 448409, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='enrollmentnotification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='enrollmentnotification',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
