# Generated by Django 3.1 on 2020-09-10 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_auto_20200908_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': 'Instructor'},
        ),
        migrations.AlterModelOptions(
            name='learner',
            options={'verbose_name_plural': 'Learner'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profile'},
        ),
    ]
