# Generated by Django 3.1 on 2020-09-12 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0003_auto_20200910_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
