# Generated by Django 3.1 on 2020-09-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_auto_20200912_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
